---
version: "3.4"
services:
  facade:
    build:
      context: .
    volumes:
      - ./:/opt/app
    environment:
      SCRIPT_CLIENT_MUTUALLY_DEFINED: ${SCRIPT_CLIENT_MUTUALLY_DEFINED}
    ports:
      - 8000:8000
